import type { Source } from "../api/client";

interface Props {
  source: Source;
}

/**
 * Renders a single cited source chunk.
 * Citation format [filename, p.N] is generated by the GENERATE_USER prompt —
 * do not change this display without coordinating with prompts.py.
 */
export default function SourceCard({ source }: Props) {
  return (
    <div
      style={{
        border: "1px solid #d1d5db",
        borderRadius: 6,
        padding: "10px 14px",
        marginBottom: 8,
        backgroundColor: "#f9fafb",
        fontSize: 13,
      }}
    >
      <div
        style={{
          fontWeight: 600,
          marginBottom: 4,
          color: "#374151",
        }}
      >
        {source.document_name} — p.{source.page_number}
      </div>
      <div
        style={{
          color: "#6b7280",
          lineHeight: 1.5,
          maxHeight: 80,
          overflow: "hidden",
          textOverflow: "ellipsis",
        }}
      >
        {source.content}
      </div>
    </div>
  );
}
